server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234

  thymeleaf:
    prefix : classpath:/templates/
    suffix : .html
    cache : false
    check-template-location : true


#  mvc:
#    view:
#      prefix: /templates/
#      suffix: .mustache

  jpa:
    hibernate:
      ddl-auto: create #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 985224645316-ctpdrv84dd7uncunsfvrr66c0f66gdmr.apps.googleusercontent.com
            client-secret: Fyv61bfuMsqDG6iLoVLOoVd-
            scope:
              - email
              - profile

          facebook:
            client-id: 955019588668914
            client-secret: 695a9a306b0c160cd8ba5e1983cae88f
            scope:
              - email
              - public_profile

